### ISSUE TITLE
Filter Error Symfony\Component\Ldap\Exception\LdapException: Could not complete search with dn "OU=Contacts,OU=Contacts,DC=xxx,DC=xxx", query "(&(&(objectClass=contact))(|(=*)))" and filters "*". LDAP error was [-7] Bad search filter.

### ISSUE THREAD

**Issue by Qualityadmin** [nextcloud/ldap_contacts_backend#16]
Hey, having some problem with setting this up on our Owncloud solution.  
getting this error when specifying a filter or if leaving it blank.  I have tried using the interactive menu, adding the filter= option and leaving it blank to run as default and all return the same value.  its as if the filter= option and the interactive menu arent applying the filter i provide and the default one has an error causing it to fail.  Below is an extract from the logs:

`Symfony\Component\Ldap\Exception\LdapException: Could not complete search with dn "OU=Contacts,DC=xxx,DC=xxx", query "(&(&(objectClass=contact))(|(=*)))" and filters "*". LDAP error was [-7] Bad search filter.

    /var/www/nextcloud/apps/ldap_contacts_backend/lib/Service/LdapQuerent.php - line 75:

    Symfony\Component\Ldap\Adapter\ExtLdap\Query->execute()

    /var/www/nextcloud/apps/ldap_contacts_backend/lib/Service/LdapQuerent.php - line 93:

    OCA\LDAPContactsBackend\Service\LdapQuerent->fetchAll()

    /var/www/nextcloud/apps/ldap_contacts_backend/lib/Service/LdapCardBackend.php - line 63:

    OCA\LDAPContactsBackend\Service\LdapQuerent->find()

    /var/www/nextcloud/apps/ldap_contacts_backend/lib/Service/ContactsAddressBook.php - line 84:

    OCA\LDAPContactsBackend\Service\LdapCardBackend->searchCards()

    /var/www/nextcloud/lib/private/ContactsManager.php - line 52:

    OCA\LDAPContactsBackend\Service\ContactsAddressBook->search()

    /var/www/nextcloud/lib/private/Contacts/ContactsMenu/ContactsStore.php - line 87:

    OC\ContactsManager->search()

    /var/www/nextcloud/lib/private/Contacts/ContactsMenu/Manager.php - line 70:

    OC\Contacts\ContactsMenu\ContactsStore->getContacts()

    /var/www/nextcloud/core/Controller/ContactsMenuController.php - line 61:

    OC\Contacts\ContactsMenu\Manager->getEntries()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OC\Core\Controller\ContactsMenuController->index()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()`

**Comment by blizzz** [comment]
As this seems to be a configuration issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
