### ISSUE TITLE
LDAP connectivity settings

### ISSUE THREAD

**Issue by blizzz** [nextcloud/ldap_contacts_backend#2]
for the first package of #1

### Settings overview 

Collapsed overview (to be placed below the currently existing LDAP settings):

![settings overview](https://user-images.githubusercontent.com/2184312/73279919-10e9c880-41ee-11ea-8983-35d8f458b5a0.png)

Not very spectacular. It is a list of collapsed, configured LDAP connections that should be used a contacts backend, plus the option to add one.

---

### Full view of a backend configuration

![Connection full view](https://user-images.githubusercontent.com/2184312/73351563-8d80b380-428f-11ea-968f-6eb8d5a1667a.png)

The connection details would be collapsed by default. The thought behind them is: if an existing LDAP configuration is being used, look up the settings from there. If something else is necessary, like a different service user for permissions, this can be unlocked or unbound and we copy the stuff over that we need. The button and info text will not be shown. These fields are also necessary when we have a connection entirely separate from a user backend one.

The rest is as above.

--- 

### New  connection picker model

![Add LDAP backend](https://user-images.githubusercontent.com/2184312/73280552-febc5a00-41ee-11ea-9069-359b5406c8f9.png)

Lists the available configurations from the user backend and an option for a new connection. Straight forward.

**Comment by rullzer** [comment]
@blizzz be sure to invoke our vue wizards when constructing the UI. To share load and to make sure we use the same stuff everywhere

**Comment by blizzz** [comment]
> @blizzz be sure to invoke our vue wizards when constructing the UI. To share load and to make sure we use the same stuff everywhere

@skjnldsv @ChristophWurst @juliushaertl I have backend bits for the config (#3), now the UI would be next thing to tackle. Is one of you up to contributing to it?

**Comment by skjnldsv** [comment]
Scheduled for 19?

**Comment by rullzer** [comment]
@blizzz I think with the work from @ChristophWurst you can just have it hook into contacts directly by implementing an some backend stuff

**Comment by blizzz** [comment]
> Scheduled for 19?

yes

**Comment by blizzz** [comment]
> @blizzz I think with the work from @ChristophWurst you can just have it hook into contacts directly by implementing an some backend stuff

what exactly? The config is specific to LDAP.

**Comment by blizzz** [comment]
So we go with occ config for now, that is accepted. I close this, but can be picked up (and reopened) anytime if someone is up to.
