### ISSUE TITLE
Cannot configure LDAP, allowed memory size exhausted

### ISSUE THREAD

**Issue by MohammedNoureldin** [nextcloud/ldap_contacts_backend#33]
Hello,

in Nextcloud version 22, trying to execute:

    sudo -u www-data php occ ldap_contacts:add --interactive SomeText

exits with the following fatal error:

> Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 446464 bytes) in /var/www/html/3rdparty/composer/autoload_real.php on line 37

Any possible solutions?

I tried to make the `memory_limit` in  /usr/local/etc/php/php.ini-production and development higher, but that did not help.

**Comment by MohammedNoureldin** [comment]
@blizzz could you check this pelase?

**Comment by MohammedNoureldin** [comment]
UPDATE, apparently I got the command to work (at least I get no error now), I will edit this later and paste how (basically by adding a new php.ini file with the new `memory_limit`). Though, this is still a work around, and another fix should be merged.

Nevertheless, I still have no idea how this should be used. Should I see my LDAP contacts in the "normal" LDAP contacts add-on? Or will they be available only in the new list in the right corner? In this case, that means they will not be available for `CardDav`?

**Comment by MohammedNoureldin** [comment]
Well, I will close this because my issue is not the memory limit anymore. However, this addon simply does not work, unfortunately. I really like it, but I just cannot get the simplest for of LDAP contacts to appear in a simple address book.

The solution for the memory error is exactly this comment: https://github.com/nextcloud/docker/issues/1413#issuecomment-890367203

**Comment by blizzz** [comment]
> Nevertheless, I still have no idea how this should be used. Should I see my LDAP contacts in the "normal" LDAP contacts add-on? Or will they be available only in the new list in the right corner? In this case, that means they will not be available for CardDav?

They are searchable in the contacts menu, with the option to import it into your personal addressbook.

**Comment by MohammedNoureldin** [comment]
Thank you for your reply, @blizzz. The problem is that I even don't get that option to copy the contacts to my addeess book. The icon does not appear next tobthe contacts in the menu. Do you have any idea why can that happ

**Comment by MohammedNoureldin** [comment]
Can't the virtual addressbook generated by this plugin be viewed inside the contacts add-on (without importing every single contact manually)? This will give the ability to share this addressbook that has all LDAP contacts using CardDav.
